homepage/api/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from . import views


app_name = 'api'

urlpatterns = [
    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/<pk>/', views.DetailedView.as_view(), name='news_detail'),
    path('news-create/', views.CreateNewsView.as_view(), name='news_create'),
    path('news-update/<pk>/', views.UpdateNewsView.as_view(), name='news_update'),
    path('news-delete/<pk>/', views.DeleteNewsView.as_view(), name='news_delete'),
    path('advertisement/', views.AdListView.as_view(), name='advertisement'),
    path('advertisement/<pk>/', views.SimpleAdDetailedView.as_view(), name='simplead_detail'),
    path('advertisement-create/', csrf_exempt(views.CreateSimpleAdView.as_view()), name='simplead_create'),
    path('advertisement-create/', views.CreateSimpleAdView.as_view(), name='simplead_create'),

]

homepage/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'homepage'

urlpatterns = [
    path('', views.IndexClassView.as_view(), name='index'),
    path('show_all_ads/', views.ShowAds.as_view(), name='show_all_ads'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', views.Register.as_view(), name='register'),
    path('new_ad/', views.NewAd.as_view(), name='new_ad'),
    path('<int:year>/<int:month>/<int:day>/<slug:ad>/', views.AdDetail.as_view(), name='ad_detail'),
    path('edit/', views.Edit.as_view(), name='edit'),
    path('forum/', views.ForumView.as_view(), name='forum'),
    path('<int:id>/<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('create_topic/', views.CreateTopic.as_view(), name='create_topic'),
    path('local_news/', views.LocalNews.as_view(), name='local_news'),
    path('all_cityhall_news/', views.CityhallNews.as_view(), name='all_cityhall_news'),
    path('gallery/', views.GalleryView.as_view(), name='gallery'),
    path('add_image/', views.AddImage.as_view(), name='add_image'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls', namespace='homepage')),
    path('', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('api/', include('homepage.api.urls', namespace='api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

homepage/api/views.py
from datetime import datetime
from django.views import View
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404

from ..models import News, SimpleAd
from .serializers import NewsSerializer, SimpleAdSerializer
from rest_framework import generics, status
from rest_framework.authentication import BasicAuthentication
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated

from django.views import View
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404
from rest_framework import generics
from ..models import News, SimpleAd
from .serializers import NewsSerializer, SimpleAdSerializer
from rest_framework.authentication import BasicAuthentication
from rest_framework.views import APIView
from rest_framework.response import Response

from rest_framework.permissions import IsAuthenticated


class NewsListView(generics.ListAPIView):
    queryset = News.objects.all()
    serializer_class = NewsSerializer

class DetailedView(APIView):

    def get(self, request, pk):
        queryset = get_object_or_404(News, pk=pk)
        serializer = NewsSerializer(queryset)
        return Response(serializer.data)

class CreateNewsView(APIView):
    permission_classes = (IsAuthenticated,)

class DetailedView(APIView):

    def get(self, request, pk):
        queryset = get_object_or_404(News, pk=pk)
        serializer = NewsSerializer(queryset)
        return Response(serializer.data)

class CreateNewsView(APIView):



    permission_classes = (IsAuthenticated,)

    def post(self, request):
        serializer = NewsSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
        return Response(serializer.data)

class UpdateNewsView(APIView):
    permission_classes = (IsAuthenticated,)
    def get(self, request, pk):
        queryset = get_object_or_404(News, pk=pk)
        serializer = NewsSerializer(queryset)
        return Response(serializer.data)

    def post(self, request, pk):
        queryset = get_object_or_404(News, pk=pk)
        serializer = NewsSerializer(instance=queryset, data=request.data)
        if serializer.is_valid():
            serializer.save()
        return Response(serializer.data)

class DeleteNewsView(APIView):
    permission_classes = (IsAuthenticated,)
    def get(self, request, pk):
        queryset = get_object_or_404(News, pk=pk)
        serializer = NewsSerializer(queryset)
        return Response(serializer.data)

    def delete(self, request, pk):
        queryset = get_object_or_404(News, pk=pk)
        queryset.delete()
        return Response('Succesfully deleted news!')
#
#
#
class AdListView(View):

    def get(self, request):
        simple_ads = SimpleAd.objects.all()
        serializer = SimpleAdSerializer(simple_ads, many=True)
        return JsonResponse(serializer.data, safe=False)


class SimpleAdDetailedView(View):

    def get(self, request, pk):
        queryset = get_object_or_404(SimpleAd, pk=pk)
        serializer = SimpleAdSerializer(queryset)
        return JsonResponse(serializer.data, safe=False)

class CreateSimpleAdView(APIView):
    authentication_classes = (BasicAuthentication, )
    permission_classes = (IsAuthenticated,)

    def post(self, request):
        serializer = SimpleAdSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            print(serializer.errors)

homepage/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.decorators import method_decorator
from .models import News, Movie, MovieSpectacles, SimpleAd, Profile, ForumTopic, ForumResponse, User, Gallery
from .forms import SimpleAdForm, LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm, CreateTopicForm, CreateResponseForm, AddImageToGalleryForm
from .custom_webscraper import olawa24_scraper, tuolawa_scraper, kino_odra_scraper, go_kino_scraper, um_olawa_scraper
from django.utils import timezone
from django.shortcuts import redirect
from django.views import View


class IndexClassView(View):
    def get(self, request):

        olawa24_news = News.olawa24_manager.all().order_by('-date_of_publication')[:10]
        tuolawa_news = News.tuolawa_manager.all().order_by('-date_of_publication')[:10]
        umolawa_news = News.umolawa_manager.all().order_by('-date_of_publication')[:5]
        kino_odra_movies = Movie.kino_odra_manager.all().filter(day_of_spectacle=timezone.now().replace(hour=0, minute=0, second=0, microsecond=0))
        kino_odra_spectacles = {}
        for one_movie in kino_odra_movies:
            spectacle_dates_list = []
            for spectacle_date in one_movie.all_spectacles.all():
                spectacle_dates_list.append(spectacle_date.date.strftime('%H:%M'))
            kino_odra_spectacles[one_movie] = spectacle_dates_list

        go_kino_movies = Movie.gokino_manager.all().filter(day_of_spectacle=timezone.now().replace(hour=0, minute=0, second=0, microsecond=0))
        go_kino_spectacles = {}
        for one_movie2 in go_kino_movies:
            spectacle_dates_list2 = []
            for spectacle_date2 in one_movie2.all_spectacles.all():
                spectacle_dates_list2.append(spectacle_date2.date.strftime('%H:%M'))
            go_kino_spectacles[one_movie2] = spectacle_dates_list2

        return render(request, 'homepage/index.html', {'olawa24_news': olawa24_news,
                                                       'tuolawa_news': tuolawa_news,
                                                       'umolawa_news': umolawa_news,
                                                       'kino_odra_movies': kino_odra_spectacles,
                                                       'go_kino_spectacles': go_kino_spectacles})


class ShowAds(View):
    def get(self, request):
        all_ads = SimpleAd.objects.all().order_by('-id')
        return render(request, 'homepage/show_all_ads.html', {'all_ads': all_ads})


class AdDetail(View):
    def get(self, request, year, month, day, ad):
        ad = get_object_or_404(SimpleAd,
                               slug=ad,
                               date_of_publication__year=year,
                               date_of_publication__month=month,
                               date_of_publication__day=day)
        return render(request, 'homepage/ad_detail.html', {'ad': ad})

# basic login function,it was replaced by integrated in django loginview, I am leaving it here just to know how to do it
# def user_login(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(username=cd['username'],
#                                 password=cd['password'])
#             if user is not None:
#                 if user.is_active:
#                     login(request, user)
#                     messages.success(request, 'Uwierzytelnienie zakończyło się sukcesem')
#                     # return HttpResponse('Uwierzytelnienie zakończyło się sukcesem')
#                 else:
#                     messages.success(request, 'Konto jest zablokowane')
#                     # return HttpResponse('Konto jest zablokowane')
#             else:
#                 messages.success(request, 'Nieprawidłowe dane uwierzytelniające')
#                 # return HttpResponse('Nieprawidłowe dane uwierzytelniające')
#     else:
#         form = LoginForm()
#     return render(request, 'homepage/login.html', {'form': form})


class Register(View):
    def get(self, request):
        user_form = UserRegistrationForm()
        return render(request, 'homepage/register.html', {'user_form': user_form})

    def post(self, request):
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            profile = Profile.objects.create(user=new_user)
            messages.success(request, 'Uwierzytelnienie zakończyło się sukcesem')
            return render(request, 'homepage/register_done.html', {'new_user': new_user})


class NewAd(View):
    all_ads = SimpleAd.objects.all()
    def post(self, request):
        ad_form = SimpleAdForm(user=request.user,data=request.POST, files=request.FILES)
        if ad_form.is_valid():
            new_ad = ad_form.save(commit=False)
            new_ad.author = request.user
            new_ad.save()
            ad_form = SimpleAdForm(user=request.user)
            return redirect('homepage:show_all_ads')

    def get(self, request):
        ad_form = SimpleAdForm(user=request.user)
        return render(request, 'homepage/new_ad.html', {'ad_form': ad_form,
                                                        'all_ads': self.all_ads})

class Edit(View):

    @method_decorator(login_required)
    def post(self, request):
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile,
                                       data=request.POST,
                                       files=request.FILES)
        if user_form.is_valid():
            user_form.save()
            profile_form.save()
        return redirect('homepage:index')

    @method_decorator(login_required)
    def get(self, request):
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
        return render(request, 'homepage/edit.html', {'user_form': user_form,
                                                      'profile_form': profile_form})


class ForumView(View):
    def get(self, request):
        all_topics = ForumTopic.objects.all().order_by('-id')
        return render(request, 'homepage/forum.html', {'all_topics': all_topics})


class CreateTopic(View):
    @method_decorator(login_required)
    def post(self, request):
        new_topic_form = CreateTopicForm(user=request.user, data=request.POST)
        if new_topic_form.is_valid():
            new_topic = new_topic_form.save(commit=False)
            new_topic.author = request.user
            new_topic.save()
            new_topic_form = CreateTopicForm(user=request.user)
            return redirect('homepage:forum')

    @method_decorator(login_required)
    def get(self, request):
        new_topic_form = CreateTopicForm(user=request.user)
        return render(request, 'homepage/create_topic.html', {'new_topic_form': new_topic_form})


class PostDetail(View):
    def get(self, request, slug, id):
        post_topic = get_object_or_404(ForumTopic,
                                       slug=slug,
                                       id=id)

        try:
            post_responses = ForumResponse.objects.select_related('author__profile').filter(topic=post_topic).order_by('date_of_publication')
        except AttributeError:
            post_responses = ''
        try:
            topic_author_thumbnail_url = post_topic.author.profile.thumbnail.url
        except AttributeError:
            topic_author_thumbnail_url = None

        new_response_form = CreateResponseForm(user=request.user)
        return render(request, 'homepage/post_detail.html', {'post_topic': post_topic,
                                                             'post_responses': post_responses,
                                                             'thumbnail_url': topic_author_thumbnail_url,
                                                             'new_response_form': new_response_form})

    @method_decorator(login_required)
    def post(self, request, id, slug):
        post_topic = get_object_or_404(ForumTopic,
                                       slug=slug,
                                       id=id)
        try:
            post_responses = ForumResponse.objects.select_related('author__profile').filter(topic=post_topic).order_by('date_of_publication')
        except AttributeError:
            post_responses = ''
        try:
            topic_author_thumbnail_url = post_topic.author.profile.thumbnail.url
        except AttributeError:
            topic_author_thumbnail_url = None

        new_response_form = CreateResponseForm(user=request.user, data=request.POST)
        if new_response_form.is_valid():
            new_response = new_response_form.save(commit=False)
            new_response.author = request.user
            new_response.topic = post_topic
            new_response.save()
            new_response_form = CreateResponseForm(user=request.user)
        return render(request, 'homepage/post_detail.html', {'post_topic': post_topic,
                                                             'post_responses': post_responses,
                                                             'thumbnail_url': topic_author_thumbnail_url,
                                                             'new_response_form': new_response_form})


class LocalNews(View):
    def get(self, request):
        olawa24_news = News.olawa24_manager.order_by('-date_of_publication')

homepage/templates/homepage/ad_detail.html
{% extends "homepage/base.html" %}
{% block title %}{{ ad.title }}{% endblock %}
{% load thumbnail %}
{% load l10n %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="col-12-center">
                    <p style="font-size: 25px" align="center">{{ ad.title }}</p>
                    <hr>
                </div>
                <div class="col-12-no-brdr">
                    <p>Autor ogłoszenia: <strong>{{ ad.author }}</strong></p>
                    <p>Dodano: {% localize on %}{{ ad.date_of_publication}}{% endlocalize %}</p>
                    <p>Cena: {{ ad.price }} zł</p>
                    <hr>
                </div>
                <div class="col-12-no-brdr">
                    <div>{{ ad.body|safe }} <!----------------SAFETY ISSUE ----------------------------------------></div>
                    <div class="col-12-center">
                        {% if ad.image %}
                        <img src="{{ ad.resized_photo.url }}" style="max-width: 100%">
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

homepage/templates/homepage/add_image.html
{% extends "homepage/base.html" %}
{% block title %}moj blog{% endblock %}
{% load thumbnail %}
{% load static %}


{% block content %}
<div class="container">
    <div class="row">
      <div class="col-12">
          <form action="." method="post" enctype="multipart/form-data">
              {{new_image_form.as_p}}
              {% csrf_token %}
              <p><input type="submit" value="Dodaj zdjęcie do galerii"></p>
          </form>
      </div>
    </div>
</div>
{% endblock %}

homepage/templates/homepage/all_cityhall_news.html
{% extends "homepage/base.html" %}

{% block title %}Ogłoszenia z Urzędu Miasta{% endblock %}


{% block premieres %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="col-12-center">
                <h2>Wiadomości z Urzędu Miasta Oława</h2>
                <hr>
            </div>
            <div class="col-12-no-brdr">
                {% for news in umolawa_news %}
                    <h6 class="title-news"><a href={{ news.link }}>{{ news.title }}</a></h6>
                    <p class="container-date">Opublikowano: {{ news.date_of_publication }}</p>
                    <p>{{ news.content|truncatewords:25 }}</p>
                    <hr>
                {% endfor %}
            </div>
            <div class="col-12-center-pagination">
                <h6>{% include "homepage/pagination.html" with page=umolawa_news %}</h6>
            </div>

        </div>
    </div>
</div>


{% endblock %}

homepage/templates/homepage/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl-PL">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--    shrink-to-fit=no">-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href="{% static "css/homepage.css" %}" type='text/css' rel="stylesheet">
    <link rel="shortcut icon" href="#" />
    {% block mce %}
    {% endblock %}
</head>
<body>
    <div class="top_logo">
        <img src="{% static "images/logo_merged.png" %}" style="max-width: 100%">
    </div>
    <div class="topnav">
        <div class="topnav-main">
            <div class="row justify-content-md-center">
                <div class="col-md-auto">
                    <a class="active" href="{% url "homepage:index" %}">Główna</a>
                    <a href="{% url "homepage:local_news" %}">Wiadomości Lokalne</a>
                    <a href="{% url "homepage:all_cityhall_news" %}">Wiadomości z Urzędu Miasta</a>
                    <a href="{% url "homepage:show_all_ads" %}">Ogłoszenia lokalne</a>
                    {% if request.user.is_authenticated %}
                        <a href="{% url "homepage:new_ad" %}">Dodaj ogłoszenie</a>
                    {% endif %}
                    <a href="{% url "homepage:forum" %}">Forum dyskusyjne</a>
                    <a href="{% url "homepage:gallery" %}">Galeria zdjęć</a>
                </div>
            </div>
        </div>
        <div class="topnav-secondary">
            <div class="row justify-content-md-center">
                <div class="col-md-auto">
                    {% if request.user.is_authenticated %}
                        {% if section == "dashboard" %}class="selected"{% endif %}
                            <a href="{% url "homepage:password_change" %}">Zmień hasło</a>
                            <a href="{% url "homepage:edit" %}">Edytuj profil</a>
                            <a href="{% url "homepage:logout" %}">Wyloguj</a>
                    {% else %}
                        <a href="{% url "homepage:login" %}">Zaloguj</a>
                        <a href="{% url "homepage:register" %}">Utwórz konto</a>
                        <a href="{% url "homepage:password_reset" %}">Zapomniałeś hasła?</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                {{ message|safe }}
            {% endfor %}
        </div>
<!--    # TODO finish messages-->
    {% endif %}
    <div class="main">
            {% block content %}
            {% endblock %}
            {% block premieres %}
            {% endblock %}
            {% block cityhall_news %}
            {% endblock %}
    </div>
    <div class="footer">
        Zrealizował Tomasz Solarewicz. Sprawdź co potrafię zrobić na GITHUBie! <a href="https://github.com/mathematicianx/">LINK</a>
    </div>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</body>
</html>

homepage/templates/homepage/create_topic.html
{% extends "homepage/base.html" %}
{% block title %}Stwórz nowy temat{% endblock %}
{% load thumbnail %}
{% load static %}


{% block content %}
<div class="container">
    <div class="row">
      <div class="col-12">
          <form action="." method="post" enctype="multipart/form-data">
              {{new_topic_form.as_p}}
              {% csrf_token %}
              <p><input type="submit" value="Utwórz temat"></p>
          </form>
      </div>
    </div>
</div>
{% endblock %}

homepage/templates/homepage/edit.html
{% extends "homepage/base.html" %}
{% block title %}Edycja konta{% endblock %}
{% load thumbnail %}
{% load l10n %}


{% block content %}
     <div class="container">
            <div class="row">
                <div class="col-12">
                    <p>Edycja konta</p>
                    <p>Ustawienia możesz zmienić za pomocą poniższego formularza:</p>
                    <form action="." method="post" enctype="multipart/form-data">
                        {{ user_form.as_p }}
                        {{ profile_form.as_p }}
                        {% csrf_token %}
                        <p><input type="submit" value="Zapisz zmiany"></p>
                    </form>
                </div>
            </div>
    </div>
{% endblock %}

homepage/templates/homepage/forum.html
{% extends "homepage/base.html" %}
{% block title %}Forum dyskusyjne{% endblock %}
{% load thumbnail %}
{% load static %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12-center">
            <div class="row-forum">
                <div class="col-9-center">
                    <h2> {{ all_topics.count }} gorących tematów do dyskusji</h2>
                </div>
                <div class="col-3-center-no-brdr">
                    <a style="background-color:#2b3239" href="{% url "homepage:create_topic" %}" class="btn btn-secondary">Załóż temat</a>
                </div>
            </div>
            <div class="col-12-no-brdr">
            {% for topic in all_topics %}
                    <div class="row-forum">
                        <div class="col-9">
                            <p class="title-news"><a href="{{ topic.get_absolute_url }}">{{ topic.title }}</a></p>
                            <p class="date-cont">{{ topic.date_of_publication}} przez {{ topic.author }}</p>
                        </div>
                        <div class="col-3">
                            <p>Liczba postów: <strong>{{ topic.topic_count }}</strong></p>
                            <p>Data publikacji ostatniego posta: <br>{{ topic.last_post_date }}</p>
                        </div>
                    </div>
            {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

homepage/templates/homepage/index.html
{% extends "homepage/base.html" %}

{% block title %}Oława{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="col-12-center">
                <h2>Oława24.pl</h2>
                <p>10 najświeższych wiadomości zawsze pod ręką</p>
            </div>
            <hr>
                {% for news in olawa24_news %}
                    <p class="container-date" style="font-size:10px">{{ news.date_of_publication }}</a></p>
                    <p class="title-news" style="font-size:15px"><a href={{ news.link }}>{{ news.title|truncatechars:65  }}</a></p>
                {% endfor %}
        </div>
        <div class="col-6">
            <div class="col-12-center">
                <h2>TuOława.pl</h2>
                <p>10 najświeższych wiadomości zawsze pod ręką</p>
            </div>
            <hr>
            {% for news in tuolawa_news %}
                  <p class="container-date" style="font-size:10px">{{ news.date_of_publication }}</a></p>
                  <p class="title-news" style="font-size:15px"><a href={{ news.link }}>{{ news.title|truncatechars:65  }}</a></p>
          {% endfor %}
        </div>
    </div>
</div>
{% endblock %}
{% block premieres %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="col-12-center">
                <h2>Kino Odra</h2>
                <p>Premiery filmowe dzisiaj:</p>
            </div>
            <hr>
            {% if kino_odra_movies.items %}
                {% for key, value in kino_odra_movies.items %}
                    <span class="title-news"><a href={{ key.link }}>{{ key.title }}</a> </span>
                    <span> Ocena na Filmweb: <strong>{{ key.filmweb_score|floatformat:1 }}</strong></span>
                    <p class="date_cont">Godzina spektakli:
                    {% for v in value %}
                        {{ v }}{% if not loop.last %},{% endif %}
                    {% endfor %}
                    </p>
                {% endfor %}
            {% else %}
                <p>Niestety nie ma w dniu dzisiejszym premier filmowych w Kinie Odra. Zapraszamy jutro!</p>
            {% endif %}
        </div>
        <div class="col-6">
            <div class="col-12-center">
                <h2>GO!Kino</h2>
                <p>Premiery filmowe dzisiaj:</p>
            </div>
            <hr>
            {% if gokino_movies.items %}
                {% for key, value in gokino_movies.items %}
                    <span class="title-news"><a href={{ key.link }}>{{ key.title|truncatechars:38 }}</a>.</span>
                    <span> Ocena na Filmweb: <strong>{{ key.filmweb_score|floatformat:1 }}</strong></span>
                    <p class="date_cont">Godzina spektakli:
                    {% for v in value %}
                        {{ v }}{% if not loop.last %},{% endif %}
                    {% endfor %}
                    </p>
                {% endfor %}
            {% else %}
                <p>Niestety nie ma w dniu dzisiejszym premier filmowych w GO!Kinie. Zapraszamy jutro!</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}
{% block cityhall_news %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="col-12-center"><h2>Urząd Miasta Oława</h2></div>
            <hr>
            {% for news in umolawa_news %}
              <p class="title-news"><a href={{ news.link }}>{{ news.title }}</a></p>
              <p class="date_cont">Opublikowano: {{ news.date_of_publication }}</p>
              <p>{{ news.content|truncatewords:25 }}</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

homepage/templates/homepage/local_news.html
{% extends "homepage/base.html" %}

{% block title %}Lokalne wiadomości{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-6">
            <div class="col-12-center">
                <h2>Oława24.pl</h2>
                <p>Najświeższe wiadomości zawsze pod ręką</p>
                <hr>
            </div>
            {% for news in olawa24_news %}
                <p class="container-date">{{ news.date_of_publication }}</a></p>
                <p class="title-news"><a href={{ news.link }}>{{ news.title|truncatechars:65 }}</a></p>
            {% endfor %}
        </div>
        <div class="col-6">
            <div class="col-12-center">
                <h2>TuOława.pl</h2>
                <p>Najświeższe wiadomości zawsze pod ręką</p>
                <hr>
            </div>
            {% for news in tuolawa_news %}
                <p class="container-date">{{ news.date_of_publication }}</a></p>
                <p class="title-news"><a href={{ news.link }}>{{ news.title|truncatechars:65  }}</a></p>
            {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

homepage/templates/homepage/register_done.html
{% extends "homepage/base.html" %}
{% block title %}Witaj{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12-center">
            <h1>Witaj, {{ new_user.first_name }}</h1>
            <p>Twoje konto zostało utworzone. Możesz się już <a href="{% url "homepage:login" %}">zalogować.</a>
            </p>
        </div>
    </div>
</div>
{% endblock %}